/* =====================================================================
   VISTAS (C) — Datos maestros: navegador del modelo de master data v3.1
   (fichas, atributos, registros de la maqueta, reglas, fuentes, TX/EV,
   auditoría, convenciones, orden de carga, definiciones, cruce)
   ===================================================================== */

/* ---------- helpers ---------- */
function fv(v) {
  if (v === null || v === undefined || v === '') return '<span class="dim">—</span>';
  if (Array.isArray(v)) return v.length ? esc(v.join(' · ')) : '<span class="dim">—</span>';
  if (typeof v === 'boolean') return v ? 'V' : 'F';
  if (typeof v === 'object') { if (v.codigo !== undefined) return esc(v.codigo) + (v.fecha || v.vto ? ' · ' + fmtD(v.fecha || v.vto) : ''); if (v.tipo !== undefined && v.cantidad !== undefined) return esc(tipoEquipoInfo(v.tipo).buque) + ' ' + v.cantidad + ' × ' + v.capacidadTh + ' t/h'; return esc(JSON.stringify(v)); }
  if (typeof v === 'number') return '<span class="num">' + esc(new Intl.NumberFormat('es-AR', { maximumFractionDigits: 4 }).format(v)) + '</span>';
  if (/^\d{4}-\d{2}-\d{2}$/.test(String(v))) return fmtD(v);
  if (/^\d{4}-\d{2}-\d{2}T/.test(String(v))) return '<span class="mono">' + fmtDT(v) + '</span>';
  return esc(String(v));
}
function refTag(id, nombre) { return id ? '<span class="tag">' + esc(id) + '</span>' + (nombre ? ' ' + esc(nombre) : '') : '<span class="dim">—</span>'; }
function msTags(list) { return (list || []).length ? list.map(id => { const sit = msSituacion(id); return chip(id, sit.vigente ? (sit.porVencer ? 'warn' : 'ok') : (sit.bloquea ? 'crit' : 'warn'), sit.txt); }).join(' ') : '<span class="dim">—</span>'; }
function estadoChipMD(v) { const s = String(v || '').toLowerCase(); const ok = ['activo', 'activa', 'operativo', 'operativa', 'vigente', 'habilitada', 'habilitado', 'confirmado', 'cumplido'].includes(s); const bad = ['inactivo', 'inactiva', 'vencido', 'vencida', 'inhabilitada', 'inhabilitado', 'fuera de servicio', 'cancelado', 'suspendido', 'suspendida', 'bloqueada', 'discontinuado', 'dada de baja', 'rechazada'].includes(s); return v ? chip(v, ok ? 'ok' : bad ? 'crit' : 'warn') : '<span class="dim">—</span>'; }

/* ---------- mapeo maestro → registros de la maqueta (atributo del modelo → cómo se ve) ---------- */
function mdMap() {
  const m = md(); const E = S.ctx.entidad;
  const inE = (x) => E === 'ALL' || !x.entidad || x.entidad === E;
  const aud = m.auditoriaBase || {};
  const audCols = (r) => [{ a: 'estado_registro', f: x => estadoChipMD(x._aud?.estado_registro || aud.estado_registro) }, { a: 'version', f: x => x._aud?.version || aud.version }, { a: 'origen (auditoría)', f: x => esc(x._aud?.origen || aud.origen) }];
  const ms = (x) => msTags(x.metodo_seguro);
  const MAP = {
    'M-01': { coll: () => m.entidades, cols: [{ a: 'codigo', f: x => '<b>' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) + ' <span class="xs muted">(' + esc(x.sigla) + ')</span>' + (x.origenBU ? ' ' + chip('convertida desde BU ' + x.origenBU, 'warn') : '') }, { a: 'cuit', f: x => fv(x.cuit) }, { a: 'grupo_economico', f: x => fv(x.grupo_economico) }, { a: 'moneda_funcional', f: x => refTag(x.moneda_funcional) }, { a: 'plan_cuentas', f: x => fv(x.plan_cuentas) }, { a: 'estado', f: x => estadoChipMD(x.estado) }], extra: [{ h: 'BU (M-35)', f: x => m.bus.filter(b => b.entidad === x.id).map(b => esc(b.nombre)).join(', ') || '<span class="dim">a configurar</span>' }, { h: 'Vigencia desde', f: x => fmtD(x.vigenciaDesde) }, { h: 'Menú de Operación deshabilitado (S22)', f: x => { const t = modulosDeshabilitadosTxt('entidad', x.id); return t === 'todos' ? '<span class="muted">completo</span>' : chip(t, 'warn'); } }], nota: 'En la estructura nueva del 15/09 este maestro es la <b>entidad fiscal</b> (TyS, Terminal Timbúes, Amarre); las BU son M-35.' },
    'M-02': { coll: () => m.centrosCosto, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'unidad_negocio', f: x => refTag(x.unidad_negocio, entName(x.unidad_negocio)) }, { a: 'tipo', f: x => esc(x.tipo) }, { a: 'estado', f: x => estadoChipMD(x.estado) }], extra: [{ h: 'BU (M-35)', f: x => x.bu ? esc(buName(x.bu)) : '<span class="dim">—</span>' }] },
    'M-03': { coll: () => m.cuentasObjeto, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) + (x.calculado ? ' ' + chip('se abre por orden', 'info') : '') }, { a: 'centro_costo', f: x => refTag(x.centro_costo) }, { a: 'tipo', f: x => esc(x.tipo) }, { a: 'estado', f: x => estadoChipMD(x.estado) }], extra: [{ h: 'Objetos operativos abiertos', f: x => x.calculado ? S.orders.filter(o => !['CERRADA', 'ANULADA'].includes(o.estado)).length + ' órdenes abiertas · ' + S.orders.filter(o => o.estado === 'CERRADA').length + ' cerradas' : '' }] },
    'M-04': { coll: () => m.tiposComprobante, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'unidad_negocio', f: x => refTag(x.unidad_negocio, entName(x.unidad_negocio)) }, { a: 'centro_costo', f: x => refTag(x.centro_costo) }, { a: 'cuenta_objeto', f: x => refTag(x.cuenta_objeto) }, { a: 'estado', f: x => estadoChipMD(x.estado) }] },
    'M-05': { coll: () => [...m.departamentos.map(d => ({ ...d, _tipo: 'área' })), ...m.funciones.map(f => ({ ...f, _tipo: 'puesto' }))], cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'unidad_negocio', f: x => refTag(x.unidad_negocio || x.entidad, entName(x.unidad_negocio || x.entidad)) }, { a: 'tipo', f: x => chip(x._tipo, x._tipo === 'área' ? 'acc' : 'info') }, { a: 'metodo_seguro', f: x => x._tipo === 'puesto' ? ms(x) : '<span class="dim">—</span>' }, { a: 'estado', f: x => estadoChipMD(x.estado || 'activo') }, { a: 'area', f: x => x._tipo === 'puesto' ? refTag(x.area, byId(m.departamentos, x.area)?.nombre) : '<span class="dim">—</span>' }, { a: 'dotacion_minima_por_turno', f: x => x._tipo === 'puesto' ? fv(x.dotacion_minima_por_turno) : '<span class="dim">—</span>' }, { a: 'costo_horario_referencia', f: x => x._tipo === 'puesto' ? fmtUSD(x.costo_horario_referencia) + '/h' : '<span class="dim">—</span>' }], extra: [{ h: 'BU relacionadas (A3) · dotación (M-28)', f: x => x._tipo === 'área' ? (x.bus || []).map(buName).join(', ') : 'dotación ' + x.dotacion + ' · ' + (m.personalPropio || []).filter(p => p.puesto === x.id && p.estado === 'activo').length + ' legajos activos · ' + fmtUSD(x.costoTurno) + '/turno' }] },
    'M-06': { coll: () => [...m.clientes.map(c => ({ ...c, _tipo: 'cliente' })), ...m.proveedores.map(p => ({ ...p, _tipo: 'proveedor' }))], cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'razon_social', f: x => esc(x.razon_social || x.nombre) }, { a: 'cuit', f: x => fv(x.cuit) }, { a: 'tipo', f: x => chip(x._tipo, x._tipo === 'cliente' ? 'info' : 'acc') }, { a: 'rubro', f: x => fv(x._tipo === 'cliente' ? x.rubro : x.rubroM06) }, { a: 'condicion_fiscal', f: x => fv(x.condicion_fiscal) }, { a: 'correo', f: x => fv(x.correo) }, { a: 'condicion_pago', f: x => fv(x.condicion_pago) }, { a: 'limite_credito', f: x => x.limite_credito != null ? fmtUSD(x.limite_credito) : '<span class="dim">—</span>' }, { a: 'estado', f: x => estadoChipMD(x.estado) }], extra: [{ h: 'Instrumentos (M-16) · órdenes', f: x => x._tipo === 'cliente' ? (m.instrumentos.filter(i => i.cliente === x.id).map(i => i.id).join(', ') || '—') + ' · ' + S.orders.filter(o => o.destinatario?.id === x.id).length + ' órdenes' : esc(x.rubro) }] },
    'M-07': { coll: () => m.productos, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'familia', f: x => esc(x.familiaM07 || '') }, { a: 'tipo', f: x => chip(x.tipo, estadoFisico(x.id) === 'liquido' ? 'info' : 'acc', 'Define el equipo de descarga / carga: ' + (estadoFisico(x.id) === 'liquido' ? 'sistemas de bombeo' : 'grúas')) }, { a: 'presentacion', f: x => fv(x.presentacion) }, { a: 'regimen_segregacion', f: x => fv(x.regimen_segregacion) }, { a: 'unidad_base', f: x => fv(x.unidad_base) }, { a: 'unidad_conversion', f: x => fv(x.unidad_conversion) }, { a: 'regimen_regulatorio', f: x => fv(x.regimen_regulatorio) }, { a: 'densidad_tn_m3', f: x => fv(x.densidad) }, { a: 'origen', f: x => fv(x.origen) }, { a: 'color_caracteristico', f: x => fv(x.color_caracteristico) }, { a: 'tn_por_mano_turno', f: x => fv(x.tn_por_mano_turno) }, { a: 'merma_teorica_pct', f: x => x.merma_teorica_pct != null ? fmtN(x.merma_teorica_pct, 2) + ' %' : '—' }, { a: 'metodo_seguro', f: x => { const e = msEstado(x.id); return !e.requiere ? chip('No requiere', '') : e.ms ? msTags([e.ms.id]) + ' <span class="xs muted">' + e.origen + '</span>' : chip('sin MS', 'crit'); } }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'permanencia_estadistica_dias', f: x => fv(x.permanencia_estadistica_dias) }, { a: 'familia_maqueta', f: x => refTag(x.familia, famName(x.familia)) }] },
    'M-08': { coll: () => m.buques, cols: [{ a: 'numero_imo', f: x => '<b class="mono">' + esc(x.numero_imo || '—') + '</b>' }, { a: 'nombre', f: x => '<b>' + esc(x.nombre) + '</b> <span class="tag">' + esc(x.id) + '</span>' }, { a: 'eslora_m', f: x => fv(x.eslora_m) }, { a: 'calado_m', f: x => fv(x.calado_m) }, { a: 'cantidad_bodegas', f: x => fv(x.cantidad_bodegas) }, { a: 'plan_bodegas', f: x => fv(x.plan_bodegas) }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'equipos_propios', f: x => x.equipos_propios ? fv(x.equipos_propios) : chip('gearless', '') }], extra: [{ h: 'Escalas (M-17)', f: x => S.ops.lineups.filter(l => l.buqueId === x.id).map(l => '<span class="mono">' + esc(l.id) + '</span>').join(' ') || '—' }] },
    'M-09': { coll: () => m.plantas, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'unidad_negocio', f: x => refTag(x.unidad_negocio, entName(x.unidad_negocio)) }, { a: 'tipo', f: x => esc(x.tipo) }, { a: 'provincia', f: x => fv(x.provincia) }, { a: 'localidad', f: x => fv(x.localidad) }, { a: 'codigo_postal', f: x => fv(x.codigo_postal) }, { a: 'distancia_al_puerto_km', f: x => fv(x.distancia_al_puerto_km) }, { a: 'habilitaciones', f: x => fv(x.habilitaciones) }, { a: 'fecha_habilitacion', f: x => fv(x.fecha_habilitacion) }, { a: 'fecha_vencimiento', f: x => fv(x.fecha_vencimiento) }, { a: 'accion_al_vencer', f: x => fv(x.accion_al_vencer) }, { a: 'centro_costo', f: x => refTag(x.centro_costo) }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'costo_flete_referencia_tn', f: x => x.costo_flete_referencia_tn != null ? fmtN(x.costo_flete_referencia_tn, 2) + ' USD/t' : '—' }, { a: 'costo_almacenaje_tn_dia', f: x => x.costo_almacenaje_tn_dia != null ? fmtN(x.costo_almacenaje_tn_dia, 3) + ' USD/t·día' : '—' }] },
    'M-10': { coll: () => m.depositosPadre, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'planta', f: x => refTag(x.planta, planta(x.planta)?.nombre) }, { a: 'tipo', f: x => chip(x.tipo, x.tipo === 'nacional' ? '' : 'info') }, { a: 'capacidad_total_tn', f: x => fmtT(x.capacidad_total_tn) + ' t' }, { a: 'productos_aptos', f: x => fv((x.productos_aptos || []).map(p => prod(p)?.nombre || p)) }, { a: 'habilitacion', f: x => fv(x.habilitacion) }, { a: 'habilitacion_aduanera', f: x => x.habilitacion_aduanera ? fv(x.habilitacion_aduanera) : (x.tipo === 'nacional' ? '<span class="dim">no aplica</span>' : chip('falta', 'crit')) }, { a: 'habilitaciones_regulatorias', f: x => fv(x.habilitaciones_regulatorias) }, { a: 'fecha_vencimiento_habilitaciones', f: x => fv(x.fecha_vencimiento_habilitaciones) }, { a: 'dias_alerta', f: x => fv(x.dias_alerta) }, { a: 'accion_al_vencer', f: x => fv(x.accion_al_vencer) }, { a: 'metodo_seguro', f: ms }, { a: 'estado', f: x => estadoChipMD(x.estado) }], extra: [{ h: 'Ubicaciones (M-10a)', f: x => m.depositos.filter(d => d.deposito === x.id).map(d => esc(d.nombre) + ' (' + fmtT(d.capacidadT) + ' t)').join(', ') }] },
    'M-10a': { coll: () => m.depositos.filter(inE), cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'deposito', f: x => refTag(x.deposito, byId(m.depositosPadre, x.deposito)?.nombre) }, { a: 'tipo', f: x => esc(x.tipoM10a) }, { a: 'capacidad_tn', f: x => fmtT(x.capacidadT) + ' t' }, { a: 'metodo_recepcion', f: x => fv(x.metodo_recepcion) }, { a: 'calibracion', f: x => x.tipoM10a === 'tanque' ? fv(x.calibracion) : '<span class="dim">no aplica</span>' }, { a: 'metodo_seguro', f: x => (x.metodo_seguro || []).length ? ms(x) : '<span class="xs muted">hereda del depósito</span>' }, { a: 'estado', f: x => estadoChipMD(x.estadoM10a) }, { a: 'producto_asignado', f: x => { const os = reservasRecurso(x.id, null); const ps = [...new Set(os.map(rv => rv.o.producto))]; return ps.length ? fv(ps.map(p => prod(p)?.nombre)) + ' <span class="xs muted">calc.</span>' : fv(x.familias.map(famName)) + ' <span class="xs muted">aptos</span>'; } }, { a: 'ocupacion_actual_tn', f: x => { const comp = sum(reservasRecurso(x.id, null), rv => Math.max(0, rv.o.toneladas - (rv.o.ejecucion?.acumulado || 0))); return fmtT(x.ocupadoT) + ' t + ' + fmtT(comp) + ' t comprometidas <span class="xs muted">calc.</span>'; } }, { a: 'punto_de_conflicto_calidad', f: x => '<span class="dim">calc. por muestreo</span>' }], extra: [{ h: 'Fiscal (del depósito) · restricciones', f: x => (x.fiscal ? chip('Fiscal', 'info') : chip('Nacional', '')) + ' <span class="xs muted">' + esc(x.restricciones || '') + '</span>' }] },
    'M-11': { coll: () => m.transporte, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'tipo', f: x => esc(x.tipo) }, { a: 'caracteristica', f: x => fv(x.caracteristica) }, { a: 'patente', f: x => '<span class="mono">' + esc(x.patente) + '</span>' }, { a: 'descripcion', f: x => fv(x.descripcion) }, { a: 'tara_certificada_tn', f: x => fv(x.tara_certificada_tn) }, { a: 'capacidad_tn', f: x => fv(x.capacidad_tn) }, { a: 'propiedad', f: x => chip(x.propiedad, x.propiedad === 'propia' ? 'acc' : 'warn') }, { a: 'metodo_seguro', f: ms }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'transportista', f: x => refTag(x.transportista, x.transportista ? provName(x.transportista) : '') }, { a: 'aptitud_por_producto', f: x => (x.aptitud_por_producto || []).length ? fv(x.aptitud_por_producto.map(p => prod(p)?.nombre || p)) : '<span class="muted">todos</span>' }, { a: 'tara_vencimiento', f: x => x.tara_vencimiento < isoDay(0) ? chip('vencida ' + fmtD(x.tara_vencimiento), 'crit') : fv(x.tara_vencimiento) }, { a: 'checklist_vigente', f: x => fv(x.checklist_vigente) + ' <span class="xs muted">calc.</span>' }], nota: 'La planificación asigna <b>cantidad</b> de camiones desde el pool (' + m.logistica.filter(l => l.esFlota).map(l => l.nombre + ': ' + l.cantidad).join(' · ') + '); las unidades individuales se registran acá y se habilitan en portería.' },
    'M-12': { coll: () => [...m.equipos.filter(inE), ...m.logistica.filter(l => l.esMaquinaria && inE(l))], cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'tipo', f: x => chip(x.tipoM12, x.tipoM12 === 'grúa móvil' || x.tipoM12 === 'bomba' ? 'acc' : '') }, { a: 'planta', f: x => refTag(x.planta, planta(x.planta)?.nombre) }, { a: 'plan_mantenimiento', f: x => fv(x.plan_mantenimiento) }, { a: 'centro_costo', f: x => refTag(x.centro_costo, x.bu ? buName(x.bu) : '') }, { a: 'activo_fijo_asociado', f: x => fv(x.activo_fijo_asociado) }, { a: 'horometro_actual', f: x => x.horometro_actual != null ? fmtN(x.horometro_actual, 0) + ' h' : '<span class="dim">—</span>' }, { a: 'capacidad_operativa', f: x => fv(x.capacidad_operativa) }, { a: 'metodo_seguro', f: ms }, { a: 'estado', f: x => estadoChipMD((x.estado || '').toLowerCase()) + (x.mantHasta && x.estado !== 'Operativo' ? ' <span class="xs muted">hasta ' + fmtD(x.mantHasta) + '</span>' : '') }, { a: 'costo_hora_referencia', f: x => fmtUSD(x.costo_hora_referencia) + '/h' }, { a: 'proximo_mantenimiento_h', f: x => x.proximo_mantenimiento_h ? fmtN(x.proximo_mantenimiento_h, 0) + ' h' + (x.horometro_actual >= x.proximo_mantenimiento_h - 40 ? ' ' + chip('preventiva próxima', 'warn') : '') : '<span class="dim">—</span>' }], acciones: x => x.capacidadTh && !x.esMaquinaria ? btn(x.estado === 'Operativo' ? 'Marcar en mantenimiento' : 'Reactivar', 'toggle-equipo', { id: x.id }, 'sm') : '', extra: [{ h: 'Compatibilidad (familias) · dueño (M-35)', f: x => (x.familias ? x.familias.map(famName).join(', ') : 'todas') + ' · ' + esc(buName(x.bu)) }], nota: 'Grúas móviles y bombas se asignan por unidad (equipos de descarga / carga del muelle, S14); palas, tolvas y cintas por cantidad. Los equipos propios del buque están en M-08.' },
    'M-13': { coll: () => m.manos, cols: [{ a: 'proveedor', f: x => refTag(x.proveedor, provName(x.proveedor)) }, { a: 'convenio', f: x => fv(x.convenio) }, { a: 'categoria', f: x => '<b>' + esc(x.categoria) + '</b> <span class="tag">' + esc(x.id) + '</span>' }, { a: 'composicion_roles', f: x => fv(x.composicion_roles) }, { a: 'tarifa_mano', f: x => fmtUSD(x.tarifa_mano) }, { a: 'unidad_tarifa', f: x => fv(x.unidad_tarifa) }, { a: 'moneda', f: x => refTag(x.moneda) }, { a: 'centro_costo', f: x => refTag(x.centro_costo) }, { a: 'metodo_seguro', f: ms }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'vigencia_desde_hasta', f: x => fv(x.vigencia_desde_hasta) }], extra: [{ h: 'Productos (familias)', f: x => x.familias.map(famName).join(', ') }] },
    'M-14': { coll: () => m.servicios, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) + (x.pendiente ? ' ' + chip('alcance pendiente', 'warn') : '') }, { a: 'componentes', f: x => fv(x.componentesM14) }, { a: 'origen', f: x => fv(x.origenM14) }, { a: 'recursos', f: x => fv(x.recursos) }, { a: 'controles', f: x => '<span class="xs">' + esc(x.controles) + '</span>' }, { a: 'etapas', f: x => '<span class="xs">' + esc(x.etapas) + '</span>' }, { a: 'unidad_cuantificacion', f: x => fv(x.unidad_cuantificacion) }, { a: 'metodo_seguro', f: ms }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'unidades_negocio', f: x => fv(x.nivel === 'entidad' ? x.ambito.map(e => 'Entidad ' + entName(e)) : x.busPrestadoras.map(buName)) }, { a: 'nivel', f: x => chip(x.nivel, x.nivel === 'entidad' ? 'acc' : 'info') }, { a: 'rol_cierre', f: x => chip(rolName(x.cierre), x.cierre === 'DEP' ? 'acc' : 'info') }, { a: 'requiere_producto', f: x => fv(!!x.requiereProducto) }] },
    'M-15': { coll: () => m.tarifas, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'tipo_servicio', f: x => refTag(x.tipo_servicio, srv(x.tipo_servicio)?.nombre) + ' <span class="xs muted">componente ' + esc(compName(x.componente)) + '</span>' }, { a: 'cliente', f: x => x.cliente ? refTag(x.cliente, cli(x.cliente)?.nombre) : '<span class="muted">general (interno / grupo)</span>' }, { a: 'producto', f: x => x.producto ? fv(x.producto.map(p => prod(p)?.nombre || p)) : '<span class="muted">todos</span>' }, { a: 'almacenaje', f: x => fv(x.almacenaje) }, { a: 'precio', f: x => fmtN(x.precio, 2) }, { a: 'unidad_tarifa', f: x => fv(x.unidad_tarifa) }, { a: 'moneda', f: x => refTag(x.moneda) }, { a: 'vigencia_desde_hasta', f: x => fmtD(x.vigencia_desde) + ' → ' + fmtD(x.vigencia_hasta) }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'equivalencia_unidad', f: x => fv(x.equivalencia_unidad) }], extra: [{ h: 'Instrumento (M-16)', f: x => '<span class="mono">' + esc(x.contrato) + '</span>' }], nota: 'Las tarifas se publican desde las tarifas por componente de cada instrumento (M-16 ★ tarifas_por_componente); la orden congela las que aplican al crearse.' },
    'M-16': { coll: () => m.instrumentos, cols: [{ a: 'numero', f: x => '<b class="mono">' + esc(x.id) + '</b>' + (x.creadoDesde ? ' ' + chip('desde la orden', 'warn') : '') }, { a: 'cliente', f: x => x.cliente ? refTag(x.cliente, cli(x.cliente)?.nombre) : '<span class="muted">' + (x.interno ? 'BU de la misma entidad' : 'empresas del grupo') + '</span>' }, { a: 'tipo', f: x => chip(x.tipoM16 || (x.padre ? 'adenda' : 'contrato'), x.padre ? 'warn' : 'acc') + ' <span class="xs muted">' + esc(x.tipo) + '</span>' }, { a: 'servicios_incluidos', f: x => fv(x.servicios.map(s => srv(s)?.nombre || s)) }, { a: 'ritmo_contractual_tn_turno', f: x => x.ritmo_contractual_tn_turno ? fmtT(x.ritmo_contractual_tn_turno) + ' t/turno <span class="xs muted">(' + fmtT(x.condiciones?.ritmoComprometido) + ' t/día)</span>' : '—' }, { a: 'tolerancia_entre_balanzas_pct', f: x => fv(x.tolerancia_entre_balanzas_pct) }, { a: 'merma_reconocida_pct', f: x => x.condiciones?.toleranciaMermaPct != null ? fmtN(x.condiciones.toleranciaMermaPct, 1) + ' %' : '<span class="muted">general</span>' }, { a: 'perdida_de_identidad', f: x => fv(x.perdida_de_identidad) }, { a: 'documento', f: x => fv(x.documento) }, { a: 'sla_aviso_dias_min_max', f: x => fv(x.sla_aviso_dias_min_max) }, { a: 'contrato_padre', f: x => refTag(x.padre) }, { a: 'volumen_comprometido_periodo_tn', f: x => x.volumen_comprometido_periodo_tn ? fmtT(x.volumen_comprometido_periodo_tn) + ' t' : '—' }, { a: 'tope_cupos_diario', f: x => fv(x.tope_cupos_diario) }, { a: 'plazo_almacenaje_bonificado_dias', f: x => fv(x.condiciones?.franquiciaDias) }, { a: 'vigencia_desde', f: x => fmtD(x.vigenciaDesde) }, { a: 'vigencia_hasta', f: x => fmtD(x.vigenciaHasta) }, { a: 'estado', f: x => estadoChipMD(x.vigenciaHasta >= isoDay(0) ? 'vigente' : 'vencido') }, { a: 'modalidad_por_defecto', f: x => fv(x.modalidad_por_defecto) }, { a: 'condicion_aduanera_prevista', f: x => fv(x.condicion_aduanera_prevista) }, { a: 'espacio_asignado', f: x => (x.espacio_asignado || []).length ? fv(x.espacio_asignado.map(recNombre)) : '—' }, { a: 'productos_incluidos', f: x => x.productos ? fv(x.productos.map(p => prod(p)?.nombre || p)) : '<span class="muted">todos</span>' }, { a: 'tarifas_por_componente', f: x => Object.entries(x.tarifas).map(([k, v]) => compName(k) + ' ' + fmtN(v, 2)).join(' · ') }] },
    'M-17': { coll: () => S.ops.lineups.filter(l => E === 'ALL' || l.terminal === E), cols: [
      { a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' },
      { a: 'puerto', f: x => refTag(x.puerto, planta(x.puerto)?.nombre) },
      { a: 'buque', f: x => refTag(x.buqueId, x.buque) },
      { a: 'operador', f: x => fv(x.operador) },
      { a: 'cliente', f: x => x.cliente ? refTag(x.cliente, cli(x.cliente)?.nombre) + (x.cargas.length > 1 ? ' <span class="xs muted">+' + (new Set(x.cargas.map(c => c.cliente)).size - 1) + ' en otras cargas</span>' : '') : '<span class="dim">—</span>' },
      { a: 'shipper', f: x => fv(x.shipper) },
      { a: 'agencia', f: x => refTag(x.agencia, agName(x.agencia)) },
      { a: 'producto', f: x => x.producto ? refTag(x.producto, prod(x.producto)?.nombre) : '<span class="dim">—</span>' },
      { a: 'tipo_operacion', f: x => fv(x.tipo_operacion) },
      { a: 'plano_de_carga', f: x => '<span class="small">' + esc(x.plano_de_carga || '—') + '</span>' },
      { a: 'toneladas_nominadas_total_buque', f: x => fmtT(x.toneladas_nominadas_total_buque) + ' t' },
      { a: 'toneladas_para_tys', f: x => (x.toneladas_para_tys ? '<b>' + fmtT(x.toneladas_para_tys) + ' t</b>' : '<span class="dim">0 t</span>') + ' <span class="xs muted">calc. desde las órdenes</span>' },
      { a: 'alcance_geografico', f: x => fv(x.alcance_geografico) },
      { a: 'origen', f: x => fv(x.origen) }, { a: 'destino', f: x => fv(x.destino) },
      { a: 'eta_original', f: x => fv(x.eta_original) + (x.eta_original && x.eta_original !== x.eta ? ' <span class="xs warn-t">corrida ' + fmtN(hoursBetween(x.eta_original, x.eta), 0) + ' h</span>' : '') },
      { a: 'eta', f: x => fv(x.eta) },
      { a: 'eta_', f: x => '<span class="dim">—</span> <span class="xs muted">nombre truncado: a confirmar</span>' },
      { a: 'etb', f: x => fv(x.etb) },
      { a: 'sitio_atraque', f: x => { const os = ordenesDeOrigen('lineup', x.id).filter(o => o.plan?.recursos?.muelle); return os.length ? fv([...new Set(os.map(o => recNombre(o.plan.recursos.muelle)))]) + ' <span class="xs muted">del plan</span>' : '<span class="dim">a asignar</span>'; } },
      { a: 'operativo_vinculado', f: x => ordenesDeOrigen('lineup', x.id).map(o => osLink(o.id)).join(' ') || '<span class="dim">sin orden</span>' },
      { a: 'fuente', f: x => fv(x.fuente) }, { a: 'fecha_version', f: x => fv(x.fecha_version) },
      { a: 'estado', f: x => chip(x.estadoM17 || x.estado, x.estadoM17 === 'operando' ? 'acc' : 'info') + ' <span class="xs muted">' + esc(x.estado) + '</span>' },
      { a: 'etc', f: x => fv(x.etc) }, { a: 'orden_puerto', f: x => fv(x.orden_puerto) },
      { a: 'buque_texto_fuente', f: x => '<span class="small mono">' + esc(x.buque_texto_fuente || '—') + '</span>' },
      { a: 'cliente_texto_fuente', f: x => '<span class="small mono">' + esc(x.cliente_texto_fuente || '—') + '</span>' },
      { a: 'producto_texto_fuente', f: x => '<span class="small mono">' + esc(x.producto_texto_fuente || '—') + '</span>' },
      { a: 'homologado', f: x => fv(x.homologado) },
      { a: 'nominado_a_tys', f: x => (x.nominado_a_tys ? chip('Sí', 'ok') : chip('No', '')) + ' <span class="xs muted">se alimenta de la creación del operativo</span>' },
      { a: 'observaciones', f: x => fv(x.observaciones) },
      { a: 'cargas', f: x => x.cargas.map(c => '<span class="mono">' + esc(c.bl) + '</span> ' + fmtT(c.toneladas) + ' t' + (c.calidad ? ' · ' + esc(c.calidad) : '')).join('<br>') },
    ], nota: 'Registro operativo administrado por Logística de arribo (S10). ETB, sitio de atraque y estado operativo son el tramo portuario del modelo. <b>La nominación se alimenta de la creación del operativo</b> (revisión 16/09): al crear una orden sobre una carga de la escala se completan toneladas_para_tys, nominado_a_tys y operativo_vinculado; al anularla se revierten.' },
    'M-18': { coll: () => m.monedas, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'fuente_cotizacion', f: x => fv(x.fuente_cotizacion) }, { a: 'fecha_cotizacion', f: x => fv(x.fecha_cotizacion) }, { a: 'valor', f: x => fv(x.valor) + (x.id !== 'USD' ? ' <span class="xs muted">por USD</span>' : '') }, { a: 'estado', f: x => estadoChipMD(x.estado) }] },
    'M-19': { coll: () => m.calendario, cols: [{ a: 'planta', f: x => refTag(x.planta) }, { a: 'fecha', f: x => fmtD(x.fecha) }, { a: 'clase_dia', f: x => chip(x.clase_dia, x.clase_dia === 'hábil' ? 'ok' : 'warn') }, { a: 'turno_codigo', f: x => refTag(x.turno_codigo) }, { a: 'hora_desde', f: x => esc(x.hora_desde) }, { a: 'hora_hasta', f: x => esc(x.hora_hasta) }, { a: 'banda_horaria', f: x => fv(x.banda_horaria) }, { a: 'costo_habilitacion_inhabil', f: x => x.costo_habilitacion_inhabil ? fmtUSD(x.costo_habilitacion_inhabil) : '—' }, { a: 'estado', f: x => estadoChipMD(x.estado) }], nota: 'Generado para la Planta San Nicolás sobre el régimen de turnos (M-33), desde ayer y por 8 días. La maqueta no bloquea operar en días inhábiles: solo informa el costo de habilitación.' },
    'M-20': { coll: () => m.tolerancias, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'parametro', f: x => esc(x.parametro) }, { a: 'unidad', f: x => esc(x.unidad) }, { a: 'tolerancia_por_defecto', f: x => '<b>' + fv(x.tolerancia_por_defecto) + '</b>' }, { a: 'accion_al_exceder', f: x => chip(x.accion_al_exceder, x.accion_al_exceder.startsWith('bloquear') ? 'crit' : x.accion_al_exceder.startsWith('requerir') ? 'warn' : 'info') }, { a: 'autoriza_excepcion', f: x => fv(x.autoriza_excepcion) }, { a: 'estado', f: x => estadoChipMD(x.estado) }], extra: [{ h: 'Dónde se usa en la maqueta', f: x => '<span class="xs muted">' + esc(x.uso) + '</span>' }] },
    'M-21': { coll: () => m.agencias, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'identificacion_fiscal', f: x => fv(x.identificacion_fiscal) }, { a: 'rol', f: x => fv(x.rol) }, { a: 'agencia_domicilio', f: x => '<span class="small">' + esc(x.agencia_domicilio || '—') + '</span>' }, { a: 'agencia_telefono', f: x => '<span class="mono small nowrap">' + esc(x.agencia_telefono || '—') + '</span>' }, { a: 'agencia_email1', f: x => '<span class="small">' + esc(x.agencia_email1 || '—') + '</span>' }, { a: 'agencia_email2', f: x => '<span class="small">' + esc(x.agencia_email2 || '—') + '</span>' }, { a: 'estado', f: x => estadoChipMD(x.estado) }], extra: [{ h: 'Escalas (M-17)', f: x => S.ops.lineups.filter(l => l.agencia === x.id).length }] },
    'M-22': { coll: () => m.despachantes, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'cuit', f: x => fv(x.cuit) }, { a: 'matricula', f: x => fv(x.matricula) }, { a: 'matricula_vencimiento', f: x => fv(x.matricula_vencimiento) }, { a: 'estado', f: x => estadoChipMD(x.estado) }], nota: 'Comercial puede indicar el despachante al registrar la nacionalización de la mercadería.' },
    'M-23': { coll: () => m.matrizCalidad, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'producto', f: x => refTag(x.producto, prod(x.producto)?.nombre) }, { a: 'parametro', f: x => esc(x.parametro) }, { a: 'calidad', f: x => esc(x.calidad) }, { a: 'rangos', f: x => esc(x.rangos) }], nota: 'La calidad informada en el lineup, cupo o tren se conserva en la orden y es una dimensión de la comparativa propios / terceros.' },
    'M-24': { coll: () => m.matrizCompatibilidad, cols: [{ a: 'producto_a', f: x => refTag(x.producto_a, prod(x.producto_a)?.nombre) }, { a: 'producto_b', f: x => refTag(x.producto_b, prod(x.producto_b)?.nombre) }, { a: 'compatible', f: x => x.compatible ? chip('V', 'ok') : chip('F', 'crit') }, { a: 'condiciones', f: x => fv(x.condiciones) }], nota: 'La maqueta valida compatibilidad por familia en la ubicación; la matriz producto a producto queda registrada para el criterio de destino (A-M10).' },
    'M-25': { coll: () => [...m.muelles.filter(inE), ...(m.puntosConexion || []).filter(p => E === 'ALL' || (p.planta === 'PL-TT' ? 'TT' : 'TYS') === E)], cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'tipo', f: x => chip(x.tipoM25, x.tipoM25 === 'muelle' ? 'acc' : 'info') }, { a: 'planta', f: x => refTag(x.planta, planta(x.planta)?.nombre) }, { a: 'calado_admisible_m', f: x => fv(x.calado_admisible_m) }, { a: 'frente_de_amarre_maxima_m', f: x => fv(x.frente_de_amarre_maxima_m) }, { a: 'capacidad_tn_h', f: x => fv(x.capacidad_tn_h) }, { a: 'metodo_seguro', f: ms }, { a: 'estado', f: x => estadoChipMD(x.estadoM25) }, { a: 'productos_admitidos', f: x => fv((x.productos_admitidos || []).map(famName)) }], extra: [{ h: 'Costo/h · reservas', f: x => (x.costoHora ? fmtUSD(x.costoHora) + '/h · ' : '') + (x.tipoM25 === 'muelle' ? reservasRecurso(x.id, null).map(rv => osLink(rv.o.id)).join(' ') || '<span class="dim">sin reservas</span>' : 'muelle ' + esc(x.muelle)) }] },
    'M-26': { coll: () => m.balanzas.filter(inE), cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'planta', f: x => refTag(x.planta, planta(x.planta)?.nombre) }, { a: 'propiedad', f: x => fv(x.propiedad) }, { a: 'alcance', f: x => fv(x.alcance) }, { a: 'capacidad_tn_h', f: x => fv(x.capacidad_tn_h) }, { a: 'capacidad_camiones_h', f: x => fv(x.capacidad_camiones_h) }, { a: 'disponibilidad_por_banda_horaria', f: x => fv(x.disponibilidad_por_banda_horaria) }, { a: 'habilitada_fiscal', f: x => x.habilitada_fiscal ? chip('V', 'info') : chip('F', '') }, { a: 'habilitacion_fiscal_vto', f: x => x.habilitada_fiscal ? (x.habilitacion_fiscal_vto < isoDay(0) ? chip('vencida ' + fmtD(x.habilitacion_fiscal_vto), 'crit') : fv(x.habilitacion_fiscal_vto)) : '<span class="dim">no aplica</span>' }, { a: 'certificacion', f: x => fv(x.certificacion) }, { a: 'fecha_emision', f: x => fv(x.fecha_emision) }, { a: 'fecha_vencimiento', f: x => fv(x.fecha_vencimiento) }, { a: 'dias_aviso', f: x => fv(x.dias_aviso) }, { a: 'metodo_seguro', f: ms }, { a: 'estado', f: x => estadoChipMD(x.estadoM26) }, { a: 'prevalece_en_conciliacion', f: x => fv(x.prevalece_en_conciliacion) }, { a: 'cola_maxima_camiones', f: x => fv(x.cola_maxima_camiones) }], extra: [{ h: 'Órdenes que la usan', f: x => reservasRecurso(x.id, null).map(rv => osLink(rv.o.id)).join(' ') || '<span class="dim">—</span>' }] },
    'M-27': { coll: () => m.choferes, cols: [{ a: 'cuil', f: x => '<b class="mono">' + esc(x.cuil) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'licencia', f: x => x.licencia.vto < isoDay(0) ? chip(x.licencia.codigo + ' · vencida ' + fmtD(x.licencia.vto), 'crit') : fv(x.licencia) }, { a: 'credencial_puerto', f: x => x.credencial_puerto.vto < isoDay(0) ? chip(x.credencial_puerto.codigo + ' · vencida ' + fmtD(x.credencial_puerto.vto), 'crit') : fv(x.credencial_puerto) }, { a: 'art_seguro', f: x => fv(x.art_seguro) }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'transportista', f: x => x.transportista ? refTag(x.transportista, provName(x.transportista)) : '<span class="muted">flota propia</span>' }], nota: 'La planificación pide cantidad de choferes habilitados; las personas se registran en la ejecución / portería (VA-M27).' },
    'M-28': { coll: () => m.personalPropio, cols: [{ a: 'legajo', f: x => '<b class="mono">' + esc(x.legajo) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'tipo', f: x => fv(x.tipo) }, { a: 'puesto', f: x => refTag(x.puesto, recNombre(x.puesto)) }, { a: 'planta', f: x => refTag(x.planta, planta(x.planta)?.nombre) }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'habilitaciones', f: x => fv(x.habilitaciones) }], nota: 'La dotación se planifica por puesto (M-05) y cantidad; el legajo se asigna en la ejecución.' },
    'M-29': { coll: () => m.causasDemora, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'categoria', f: x => fv(x.categoria) }, { a: 'imputable_a', f: x => chip(x.imputable_a, x.imputable_a === 'TyS' ? 'crit' : x.imputable_a === 'fuerza mayor' ? '' : 'warn') + ' <span class="xs muted">' + esc(x.responsabilidad) + '</span>' }, { a: 'afecta_ritmo_contractual', f: x => fv(x.afecta_ritmo_contractual) }, { a: 'estado', f: x => estadoChipMD(x.estado) }] },
    'M-30': { coll: () => m.insumos, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'criticidad', f: x => chip(x.criticidad, x.criticidad === 'crítico' ? 'warn' : '') }, { a: 'stock_minimo', f: x => fv(x.stock_minimo) }, { a: 'unidad_medida', f: x => fv(x.unidad_medida) }, { a: 'presentacion', f: x => fv(x.presentacion) }, { a: 'stock_actual', f: x => (x.stock_actual < x.stock_minimo ? chip(String(x.stock_actual) + ' · bajo mínimo', 'crit') : fv(x.stock_actual)) }, { a: 'ubicacion', f: x => fv(x.ubicacion) }, { a: 'sku', f: x => fv(x.sku) }, { a: 'stockeable', f: x => fv(x.stockeable) }, { a: 'costo_unitario_referencia', f: x => fmtUSD(x.costo_unitario_referencia) }, { a: 'planta', f: x => refTag(x.planta) }, { a: 'metodo_seguro', f: x => (x.metodo_seguro || []).length ? ms(x) : '<span class="dim">opcional</span>' }, { a: 'estado', f: x => estadoChipMD(x.estado) }] },
    'M-31': { coll: () => S.ops.cupos.filter(c => E === 'ALL' || c.terminal === E), cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'fecha', f: x => fmtD(x.fecha) }, { a: 'planta', f: x => refTag(x.planta, planta(x.planta)?.nombre) }, { a: 'cliente', f: x => refTag(x.cliente, cli(x.cliente)?.nombre) }, { a: 'producto', f: x => refTag(x.producto, prod(x.producto)?.nombre) }, { a: 'contrato', f: x => refTag(x.contrato) }, { a: 'camiones', f: x => fv(x.camiones) }, { a: 'toneladas', f: x => fmtT(x.toneladas) + ' t' }, { a: 'turno', f: x => fv(x.turno) }, { a: 'tipo_movimiento', f: x => fv(x.tipo_movimiento) }, { a: 'porton', f: x => fv(x.porton) }, { a: 'confirmacion_planta', f: x => chip(x.confirmacion_planta, x.confirmacion_planta === 'confirmado' ? 'ok' : 'warn') }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'operativo_vinculado', f: x => ordenesDeOrigen('cupo', x.id).map(o => osLink(o.id)).join(' ') || '<span class="dim">sin orden</span>' }, { a: 'observaciones', f: x => fv(x.observaciones) }, { a: 'transportista', f: x => refTag(x.transportista, provName(x.transportista)) }, { a: 'calidad', f: x => fv(x.calidad) }], extra: [{ h: 'Franja', f: x => esc(x.franja) }] },
    'M-32': { coll: () => S.ops.trenes.filter(t => E === 'ALL' || t.terminal === E), cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'fecha_prevista', f: x => fmtD(x.fecha) }, { a: 'planta', f: x => refTag(x.planta, planta(x.planta)?.nombre) }, { a: 'operador_ferroviario', f: x => refTag(x.operador_ferroviario, provName(x.operador_ferroviario)) }, { a: 'cliente', f: x => refTag(x.cliente, cli(x.cliente)?.nombre) }, { a: 'producto', f: x => refTag(x.producto, prod(x.producto)?.nombre) }, { a: 'contrato', f: x => refTag(x.contrato) }, { a: 'tipo_movimiento', f: x => fv(x.tipo_movimiento) }, { a: 'vagones', f: x => fv(x.vagones) }, { a: 'toneladas', f: x => fmtT(x.toneladas) + ' t' }, { a: 'formacion', f: x => fv(x.formacion) }, { a: 'playa_desvio', f: x => fv(x.playa_desvio) }, { a: 'ventana_desde', f: x => fv(x.ventana_desde) }, { a: 'ventana_hasta', f: x => fv(x.ventana_hasta) }, { a: 'estado', f: x => estadoChipMD(x.estado) }, { a: 'operativo_vinculado', f: x => ordenesDeOrigen('tren', x.id).map(o => osLink(o.id)).join(' ') || '<span class="dim">sin orden</span>' }, { a: 'observaciones', f: x => fv(x.observaciones) }, { a: 'calidad', f: x => fv(x.calidad) }] },
    'M-33': { coll: () => m.regimenTurnos, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'orden', f: x => fv(x.orden) }, { a: 'hora_desde', f: x => esc(x.hora_desde) }, { a: 'hora_hasta', f: x => esc(x.hora_hasta) }, { a: 'duracion_h', f: x => '<b>' + x.duracion_h + ' h</b>' }, { a: 'planta', f: x => x.planta ? refTag(x.planta) : '<span class="muted">todas</span>' }, { a: 'estado', f: x => estadoChipMD(x.estado) }], nota: 'La cantidad de turnos planificados define la duración del operativo (ETC = ETB + turnos × duración); el costo de manos y personal propio se calcula por turno.' },
    'M-34': { coll: () => m.metodosSeguros, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'tipo', f: x => fv(x.tipo) }, { a: 'documento', f: x => fv(x.documento || x.procedimiento) }, { a: 'version', f: x => fv(x.version) }, { a: 'aplica_a', f: x => fv(x.aplica_a) }, { a: 'responsable', f: x => refTag(x.responsable, byId(m.departamentos, x.responsable)?.nombre) }, { a: 'fecha_vigencia_desde', f: x => fv(x.fecha_vigencia_desde) }, { a: 'fecha_vencimiento', f: x => { const s = msSituacion(x.id); return s.vigente ? (s.porVencer ? chip('vence ' + fmtD(x.vigenciaHasta) + ' · ' + s.diasRest + ' días', 'warn') : chip('vigente hasta ' + fmtD(x.vigenciaHasta), 'ok')) : chip('vencido el ' + fmtD(x.vigenciaHasta), 'crit'); } }, { a: 'dias_aviso', f: x => fv(x.dias_aviso) }, { a: 'accion_al_vencer', f: x => chip(x.accion_al_vencer, x.accion_al_vencer === 'bloquear el recurso' ? 'crit' : 'warn') }, { a: 'estado', f: x => { const s = msSituacion(x.id); return estadoChipMD(s.vigente ? (s.porVencer ? 'en revisión' : 'vigente') : 'vencido'); } }], acciones: x => btn('Registrar nueva revisión (+12 meses)', 'ms-renovar', { id: x.id }, 'sm'), extra: [{ h: 'Asignado a (producto / familia) · recursos que lo referencian', f: x => [...(x.familias || []).map(f => 'Familia: ' + famName(f)), ...(x.productos || []).map(p => 'Producto: ' + (prod(p)?.nombre || p))].join(' · ') + (recursosConMS(x.id).length ? (x.familias?.length || x.productos?.length ? ' · ' : '') + recursosConMS(x.id).map(r => esc(r.nombre)).join(', ') : '') || '<span class="dim">—</span>' }], nota: 'La habilitación de cada orden se deriva de aquí (MS del producto o de su familia). Un MS vencido con acción "bloquear el recurso" deja al recurso sin disponibilidad; dentro de los días de aviso el recurso queda "con observaciones". Órdenes afectadas hoy: ' + (S.orders.filter(o => !condiciones(o).ms.ok && o.estado !== 'CERRADA').map(o => osLink(o.id)).join(', ') || 'ninguna') + '.' },
    'M-39': { coll: () => (m.areas || []).filter(a => E === 'ALL' || a.entidad === E), cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => '<b>' + esc(x.nombre) + '</b>' }, { a: 'entidad', f: x => refTag(x.entidad, entName(x.entidad)) }, { a: 'departamento', f: x => refTag(x.departamento, byId(m.departamentos, x.departamento)?.nombre) }, { a: 'bus', f: x => (x.bus || []).length ? x.bus.map(b => refTag(b, buName(b))).join(' ') : '<span class="dim">todas</span>' }, { a: 'tipos', f: x => (x.tipos || []).map(t => chip(TIPO_NOMBRE[t] || t, 'info')).join(' ') }, { a: 'responsable_usuario', f: x => fv(x.responsable_usuario) }, { a: 'estado', f: x => estadoChipMD(x.estado) }],
      extra: [{ h: 'Recursos · capacidad', f: x => { const rs = recursosDeArea(x); return rs.length ? rs.length + ' recursos · ' + [...new Set(rs.map(y => y.tipo))].map(t => { const l = rs.filter(y => y.tipo === t); return fmtT(sum(l, y => capacidadRecurso(y.r, t).total)) + ' ' + capacidadRecurso(l[0].r, t).um; }).join(' · ') : '<span class="dim">sin recursos</span>'; } }, { h: 'Reservas vigentes', f: x => reservasDeArea(x.id).filter(r => r.estado !== 'Liberada').length || '<span class="dim">—</span>' }],
      nota: 'Cada área administra su propio sector desde el módulo <b>Mi área</b>: ve la capacidad total, hace el ABM de sus recursos por el workflow de la master data y reserva capacidad para operativos futuros referenciando un lineup, un cupo o un operativo ferroviario (revisión 16/09, S23). Muelles y equipos de descarga / carga todavía no tienen área dueña asignada (definición pendiente 23).' },
    'M-35': { coll: () => m.bus, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' + (x.sup ? ' ' + sup('S1') : '') }, { a: 'nombre', f: x => esc(x.nombre) }, { a: 'entidad', f: x => refTag(x.entidad, entName(x.entidad)) }, { a: 'centro_costo', f: x => refTag(x.cc) }, { a: 'presupuesto_anual', f: x => fmtUSD(x.presupuesto) }, { a: 'servicios_que_presta', f: x => fv(m.servicios.filter(s => s.busPrestadoras.includes(x.id)).map(s => s.nombre)) }, { a: 'convertida_en_entidad', f: x => x.convertida ? chip(entName(x.convertida.entidad) + ' desde ' + fmtD(x.convertida.vigencia), 'warn') : '<span class="dim">—</span>' }, { a: 'estado', f: x => estadoChipMD(x.convertida ? 'convertida' : 'activa') }], extra: [{ h: 'Menú de Operación deshabilitado (S22)', f: x => { const t = modulosDeshabilitadosTxt('bu', x.id); return t === 'todos' ? '<span class="muted">completo</span>' : chip(t, 'warn'); } }] },
    'M-36': { coll: () => [...Object.entries(m.matrizEjecucion).flatMap(([E2, row]) => Object.entries(row).filter(([c]) => c !== 'SRV').map(([c, b]) => ({ _k: 'mat', entidad: E2, componente: c, bu: b }))), ...m.relaciones.map(r => ({ _k: 'rel', ...r }))], cols: [{ a: 'entidad', f: x => x._k === 'mat' ? refTag(x.entidad, entName(x.entidad)) : '<span class="dim">—</span>' }, { a: 'componente', f: x => x._k === 'mat' ? esc(compName(x.componente)) : '<span class="dim">—</span>' }, { a: 'bu_ejecutora', f: x => x._k === 'mat' ? refTag(x.bu, buName(x.bu)) : '<span class="dim">—</span>' }, { a: 'relacion', f: x => x._k === 'rel' ? chip(x.nombre, x.id === 'Externa' ? 'info' : 'acc') + '<br><span class="xs muted">' + esc(x.descripcion) + '</span>' : '<span class="dim">—</span>' }, { a: 'imputacion', f: x => x._k === 'rel' ? esc(x.imputacion) : '<span class="dim">—</span>' }], nota: 'Editable en Administración › Matriz de ejecución y Relaciones e imputación.' },
    'M-37': { coll: () => [...m.estados.map(e => ({ _k: 'est', ...e })), ...m.transiciones.map(t => ({ _k: 'tr', ...t }))], cols: [{ a: 'estado', f: x => x._k === 'est' ? pill(x.id) : '<span class="dim">—</span>' }, { a: 'responsable', f: x => x._k === 'est' ? esc(x.responsable ? rolName(x.responsable) : 'Consulta') : esc(x.rol === 'cierre' ? 'Rol de cierre del servicio' : rolName(x.rol)) }, { a: 'transicion_de_a', f: x => x._k === 'tr' ? pill(x.de) + ' → ' + pill(x.a) : '<span class="dim">—</span>' }, { a: 'accion', f: x => x._k === 'tr' ? '<b>' + esc(x.accion) + '</b>' : '<span class="xs muted">' + esc(x.proximo) + '</span>' }, { a: 'validacion', f: x => x._k === 'tr' ? '<span class="small muted">' + esc(x.validacion) + '</span>' : '<span class="dim">—</span>' }, { a: 'rol_cierre_por_servicio', f: x => x._k === 'tr' && x.a === 'CERRADA' ? m.servicios.filter(s => !s.pendiente).map(s => esc(s.nombre) + ' → ' + esc(rolName(s.cierre))).join('<br>') : '<span class="dim">—</span>' }], nota: 'Editable en Administración › Workflows (rol de cierre por servicio).' },
    'M-38': { coll: () => m.roles, cols: [{ a: 'codigo', f: x => '<b class="mono">' + esc(x.id) + '</b>' }, { a: 'nombre', f: x => esc(x.nombre) + (x.sup ? ' ' + sup('S10') : '') }, { a: 'etapa_workflow', f: x => x.etapa ? 'Etapa ' + x.etapa + ' · ' + esc(m.estados.filter(e => e.responsable === x.id).map(e => e.nombre).join(', ')) : '<span class="muted">sin etapa · administra arribos</span>' }, { a: 'departamento', f: x => refTag(x.id, byId(m.departamentos, x.id)?.nombre) }, { a: 'permisos', f: x => '<span class="xs">' + esc(({ COM: 'Crear órdenes, registrar habilitaciones, cargar instrumentos o adendas, aprobar cargos al cliente, devolver / anular en su etapa, consultar todo.', PLAN: 'Asignar y confirmar recursos, regenerar recomendación, solicitar habilitación a la BU dueña, cambiar fecha de arribo, devolver / anular en su etapa, consultar todo.', OPS: 'Iniciar, ajustar el plan, registrar tickets, recursos y demoras, finalizar; cerrar servicios sin depósito; devolver / anular en su etapa.', DEP: 'Seguir ingresos, cerrar operativos con depósito (merma / excedente), devolver / anular en su etapa, consultar todo.', LAR: 'Dar de alta y modificar lineup, buques, cupos y operativos ferroviarios; consultar órdenes.', MD: 'ABM de todos los maestros; validar y publicar las altas de otros roles; otorgar o quitar a cada rol el permiso sobre cada maestro (no lo visualiza · solo consulta · puede ABM).' })[x.id] || '') + '</span>' }, { a: 'permisos_master_data', f: x => { const r = resumenPermisos(x.id); return chip('ABM ' + r.abm, 'acc') + ' ' + chip('consulta ' + r.consulta, 'info') + ' ' + chip('oculto ' + r.oculto, '') + ' ' + btn('Ver', 'mdtab', { tab: 'PERM' }, 'sm ghost'); } }, { a: 'usuario_demo', f: x => esc(x.usuario) }] },
  };
  return MAP;
}

/* ---------- catálogo de maestros (modelo + extensiones) ---------- */
function mdFichas() { return [...MODEL_FICHAS, ...MD_EXT.fichas]; }
function mdAtributos(codigo) { return [...MODEL_ATRIBUTOS, ...MD_EXT.atributos].filter(a => a.m === codigo).sort((a, b) => (+a.n || 0) - (+b.n || 0)); }
function mdReglas(codigo) { return md().reglasModelo.filter(r => !deBaja(r) && (r.maestro === codigo || (r.maestro !== 'Todos' && r.maestro.split(/\s*·\s*/).includes(codigo)))); }
function mdTx(codigo) { const f = mdFichas().find(x => x.codigo === codigo); const enFicha = new Set((f?.transacciones || '').split(/\s*·\s*/).filter(x => x.startsWith('TX-'))); return MODEL_TX.filter(t => t.maestros.split(/\s*·\s*/).includes(codigo) || enFicha.has(t.codigo)); }
const MD_TAB_TO_M = { GEN: 'M-01', COM: 'M-16', PLAN: 'M-12', PERS: 'M-05', OPS: 'M-29', DEP: 'M-10', SEG: 'M-34' };

/* ---------- Datos maestros ---------- */
function viewMD() {
  const MAP = mdMap(); const todas = mdFichas(); const rol = S.ctx.rol; const fichas = todas.filter(f => permisoMD(f.codigo, rol) !== 'oculto'); const rp = resumenPermisos(rol);
  if (S.ctx.mdTab && MD_TAB_TO_M[S.ctx.mdTab]) { S.ctx.mdM = MD_TAB_TO_M[S.ctx.mdTab]; S.ctx.mdTab = 'MAESTROS'; }
  const tab = S.ctx.mdTab || 'MAESTROS';
  const tabs = [['MAESTROS', 'Maestros (' + fichas.length + ')'], ['AREA', 'Vista por área'], ['PERM', 'Permisos por rol'], ['LOG', 'Registro de cambios' + ((S.mdLog || []).length ? ' (' + S.mdLog.length + ')' : '')], ['AUD', 'Auditoría y ciclo de vida'], ['CONV', 'Convenciones'], ['ORDEN', 'Orden de carga'], ['DEF', 'Definiciones y decisiones'], ['REGLAS', 'Reglas'], ['FUENTES', 'Fuentes de carga'], ['CRUCE', 'Cruce v2.2 → modelo → maqueta'], ['TXEV', 'TX y EV']];
  const nAttr = MODEL_ATRIBUTOS.length + MD_EXT.atributos.length;
  const nRegs = fichas.reduce((s, f) => s + ((MAP[f.codigo]?.coll() || []).length), 0);
  const permTxt = rol === 'MD' ? '<b>Máster data</b> administra todos los maestros (ABM), valida las altas de otros roles y define los permisos por rol. ' : '<b>' + esc(rolName(rol)) + '</b>: puede ABM en ' + rp.abm + ' maestros, consulta ' + rp.consulta + (rp.oculto ? ' y no visualiza ' + rp.oculto : '') + '. Los permisos los otorga Máster data. ';
  const head = pageH('Datos maestros', 'La master data de la maqueta contiene el modelo <b>' + MODEL_META.version + '</b> completo (' + MODEL_FICHAS.length + ' maestros · ' + MODEL_ATRIBUTOS.length + ' atributos · ' + md().reglasModelo.filter(r => !deBaja(r)).length + ' reglas · ' + MODEL_TX.length + ' transacciones · ' + MODEL_EV.length + ' eventos) más las extensiones de la estructura nueva del 15/09 (' + MD_EXT.fichas.length + ' maestros y ' + MD_EXT.atributos.length + ' atributos ★ Maqueta). Cada maestro tiene su ficha, sus atributos y los registros que usa el circuito. ' + permTxt + sup('S16') + ' ' + sup('S17'),
    '<span class="small muted">' + fichas.length + (fichas.length < todas.length ? ' de ' + todas.length : '') + ' maestros · ' + nAttr + ' atributos · ' + fmtT(nRegs) + ' registros · ' + MODEL_DOMINIOS.length + ' dominios</span>');
  const tabsHtml = '<div class="tabs">' + tabs.map(([id, n]) => '<button class="' + (tab === id ? 'on' : '') + '" data-action="mdtab" data-tab="' + id + '">' + n + '</button>').join('') + '</div>';
  let body = '';
  if (tab === 'MAESTROS') body = mdBrowser(MAP, fichas);
  else if (tab === 'AREA') body = mdPorArea(MAP, fichas);
  else if (tab === 'PERM') body = mdPermisos(todas);
  else if (tab === 'LOG') body = '<div class="stack"><div class="card"><div class="card-h"><h2>Registros en validación</h2><span class="small muted">altas y modificaciones de roles con permiso ABM, pendientes de que Máster data las publique</span></div>' + registrosValidacionTable(registrosEnValidacion()) + '</div>' +
    '<div class="card"><div class="card-h"><h2>Registro de cambios de la master data</h2><span class="small muted">quién, cuándo, maestro, registro y qué cambió · altas, modificaciones, bajas, validaciones y permisos</span></div>' + mdLogTable(S.mdLog || []) + '</div></div>';
  else if (tab === 'AUD') body = '<div class="stack"><div class="card"><div class="card-h"><h2>Atributos de auditoría comunes a todos los maestros</h2><span class="small muted">hoja 3 del modelo</span></div>' + table([{ h: 'Atributo', f: x => '<b class="mono">' + esc(x.atributo) + '</b>' }, { h: 'Tipo', k: 'tipo' }, { h: 'Obligatorio', k: 'obligatorio' }, { h: 'Dominio de valores', k: 'dominio' }, { h: 'Regla', f: x => '<span class="small">' + esc(x.regla) + '</span>' }], MODEL_AUDITORIA, { cls: 'compact' }) + '<p class="help" style="margin-top:8px">En la maqueta todos los registros de la carga base nacen <b>' + esc(md().auditoriaBase.estado_registro) + '</b>, origen <b>' + esc(md().auditoriaBase.origen) + '</b>, versión 1 (' + fmtD(md().auditoriaBase.creado_el) + '). Los registros creados desde las pantallas (instrumentos y adendas, lineups, buques, cupos, trenes) quedan con origen <b>manual</b> o <b>alta provisoria</b> y el usuario del rol que los cargó.</p></div>' +
    '<div class="card"><div class="card-h"><h2>Ciclo de vida del registro</h2></div>' + table([{ h: 'Estado', f: x => '<b>' + esc(x.estado) + '</b>' }, { h: 'Qué pasa', k: 'quePasa' }, { h: 'Regla', f: x => '<span class="small">' + esc(x.regla) + '</span>' }], MODEL_CICLO, { cls: 'compact' }) + '</div></div>';
  else if (tab === 'CONV') body = '<div class="card"><div class="card-h"><h2>Convenciones del modelo</h2><span class="small muted">valen para todos los maestros</span></div>' + abmBarModelo('CV') + table([{ h: 'Nº', f: x => '<b class="mono">' + esc(x.codigo) + '</b>' }, { h: 'Convención', f: x => '<b>' + esc(x.nombre) + '</b>' }, { h: 'Qué exige', k: 'exige' }, { h: 'En la maqueta', f: x => '<span class="small muted">' + esc(({ 'CV-1': 'Un solo maestro por entidad; los selectores leen siempre del maestro.', 'CV-2': 'Código interno (G1, D1, BQ-01…) + clave natural del modelo (CUIT, IMO, patente) en la ficha.', 'CV-3': 'Los obligatorios se marcan en la pestaña Atributos; la maqueta no completa vacíos con "0".', 'CV-4': 'Vencimientos con consecuencia en MS (bloquear / alertar), habilitación fiscal de balanzas y habilitaciones de depósitos.', 'CV-5': 'Tarifas y condiciones se congelan en la orden; las adendas versionan el instrumento.', 'CV-6': 'Todo lo que apunta a otro maestro se muestra como referencia (etiqueta con código).', 'CV-7': 't, t/h, t/turno, camiones/h, km, días, h declaradas en cada columna.', 'CV-8': 'Los estados gobiernan; nada se elimina (los equipos se marcan en mantenimiento, los MS se renuevan).', 'CV-9': 'Los equipos del buque son del buque (M-08), la agencia del arribo (M-17), la ocupación se calcula (M-10a).' })[x.codigo] || (x._aud ? 'agregada por Máster data' : '')) + '</span>' }, abmColModelo('CV')], md().convenciones, { cls: 'compact', rowAttr: x => deBaja(x) ? 'style="opacity:.55"' : '' }) + '</div>';
  else if (tab === 'ORDEN') body = '<div class="card"><div class="card-h"><h2>Orden de carga de los maestros</h2><span class="small muted">niveles según dependencias</span></div>' + table([{ h: 'Nivel', f: x => '<b class="mono">' + x.nivel + '</b>' }, { h: 'Maestros', f: x => x.maestros.split(' · ').map(t => { const c = t.split(' ')[0]; return '<button class="btn sm ghost" data-action="mdgo" data-m="' + esc(c) + '">' + esc(t) + '</button>'; }).join(' ') }, { h: 'Qué se hace', k: 'queSeHace' }, { h: 'Esfuerzo y bloqueo', k: 'esfuerzo' }], MODEL_ORDEN_CARGA, { cls: 'compact' }) + '<p class="help" style="margin-top:8px">Extensiones de la maqueta: M-35 BU y M-38 Usuarios y roles en nivel 1 (dependen de M-01 / M-05); M-36 Matriz de ejecución y M-37 Workflows en nivel 2 (dependen de M-14 y M-35).</p></div>';
  else if (tab === 'DEF') body = '<div class="stack"><div class="card"><div class="card-h"><h2>Definiciones previas que habilitan la carga</h2><span class="small muted">' + md().definiciones.filter(x => !deBaja(x)).length + ' definiciones</span></div>' + abmBarModelo('DF') + table([{ h: 'Nº', f: x => '<b>' + esc(x.n) + '</b>' }, { h: 'Definición', f: x => '<b>' + esc(x.definicion) + '</b>' }, { h: 'Responsable', k: 'responsable' }, { h: 'Bloquea', f: x => esc(x.bloquea) }, { h: 'Qué hay que definir', f: x => '<span class="small">' + esc(x.queDefinir) + '</span>' }, abmColModelo('DF')], md().definiciones, { cls: 'compact', rowAttr: x => deBaja(x) ? 'style="opacity:.55"' : '' }) + '</div>' +
    '<div class="card"><div class="card-h"><h2>Decisiones por maestro</h2><span class="small muted">' + md().decisiones.filter(d => !deBaja(d) && (d.estado || '').startsWith('Abierta')).length + ' abiertas · ' + md().decisiones.filter(d => !deBaja(d) && (d.estado || '').startsWith('Decidida')).length + ' decididas</span></div>' + abmBarModelo('DC') + table([{ h: 'Código', f: x => '<b class="mono">' + esc(x.codigo) + '</b>' }, { h: 'Maestro', k: 'maestro' }, { h: 'Decisión', f: x => '<b>' + esc(x.decision) + '</b>' }, { h: 'Opciones', f: x => '<span class="small">' + esc(x.opciones) + '</span>' }, { h: 'Recomendación / decisión', f: x => '<span class="small">' + esc(x.recomendacion) + '</span>' }, { h: 'Impacto si no se decide', f: x => '<span class="small muted">' + esc(x.impacto) + '</span>' }, { h: 'Estado', f: x => chip(x.estado || '—', (x.estado || '').startsWith('Decidida') ? 'ok' : 'warn') }, abmColModelo('DC')], md().decisiones, { cls: 'compact', rowAttr: x => deBaja(x) ? 'style="opacity:.55"' : '' }) + '</div>' +
    '<div class="card"><div class="card-h"><h2>Supuestos de la maqueta relacionados</h2></div><p class="small">Los supuestos S1–S16 y A1–A5 de la pantalla <b>Supuestos</b> resuelven provisoriamente varias de estas definiciones (S3 → Nº 14 métodos seguros; S6 → rol de cierre; S10 → Nº 15 tramos de administración; S12 → tolerancia de merma; S13 → solicitud a la BU dueña; S14 → equipos del buque; S15 → cambio de fecha de arribo).</p></div></div>';
  else if (tab === 'REGLAS') body = '<div class="card"><div class="card-h"><h2>Reglas por maestro</h2><span class="small muted">' + md().reglasModelo.filter(r => !deBaja(r)).length + ' reglas: validaciones, automatizaciones, alertas, ABM y parámetros</span></div>' + abmBarModelo('RG') + reglasTable(md().reglasModelo, true) + '</div>';
  else if (tab === 'FUENTES') body = '<div class="card"><div class="card-h"><h2>Mapeo de fuentes para la carga inicial</h2><span class="small muted">de qué planilla o sistema sale cada campo</span></div>' + table([{ h: 'Maestro', f: x => '<button class="btn sm ghost" data-action="mdgo" data-m="' + esc(x.maestro) + '">' + esc(x.maestro) + '</button>' }, { h: 'Atributo destino', f: x => '<b class="mono">' + esc(x.atributo) + '</b>' }, { h: 'Fuente 1 · campo', f: x => esc(x.fuente1) + (x.campo1 ? '<br><span class="xs muted">' + esc(x.campo1) + '</span>' : '') }, { h: 'Fuente 2 · campo', f: x => esc(x.fuente2) + (x.campo2 ? '<br><span class="xs muted">' + esc(x.campo2) + '</span>' : '') }, { h: 'Regla de transformación / homologación', f: x => '<span class="small">' + esc(x.regla) + '</span>' }], MODEL_MAPEO, { cls: 'compact' }) + '</div>';
  else if (tab === 'CRUCE') body = '<div class="stack"><div class="card"><div class="card-h"><h2>Estructura nueva (15/09) → modelo v3.1</h2><span class="small muted">cómo se mapea cada concepto de la maqueta</span></div>' + table([{ h: 'Concepto de la estructura nueva', f: x => '<b>' + esc(x.estructura) + '</b>' }, { h: 'Maestro del modelo', f: x => esc(x.modelo) }, { h: 'Nota', f: x => '<span class="small muted">' + esc(x.nota) + '</span>' }], MD_EXT.cruce, { cls: 'compact' }) + '</div>' +
    '<div class="card"><div class="card-h"><h2>Excel v2.2 (MD-00..MD-37) → modelo v3.1</h2></div>' + table([{ h: 'Código v2.2', f: x => '<span class="mono">' + esc(x.v22) + '</span>' }, { h: 'Maestro v2.2', k: 'nombreV22' }, { h: '→ Modelo', f: x => x.modelo.startsWith('M-') ? '<button class="btn sm ghost" data-action="mdgo" data-m="' + esc(x.modelo) + '">' + esc(x.modelo + ' ' + x.nombreModelo) + '</button>' : '<span class="dim">' + esc(x.modelo) + '</span>' }, { h: 'Qué pasó', f: x => '<span class="small">' + esc(x.quePaso) + '</span>' }], MODEL_CRUCE, { cls: 'compact' }) + '</div></div>';
  else if (tab === 'TXEV') body = '<div class="stack"><div class="card"><div class="card-h"><h2>Transacciones del circuito</h2><span class="small muted">' + MODEL_TX.length + ' transacciones · los maestros que consume cada una</span></div>' + table([{ h: 'Código', f: x => '<b class="mono">' + esc(x.codigo) + '</b>' }, { h: 'Etapa', f: x => '<span class="small">' + esc(x.etapa) + '</span>' }, { h: 'Transacción', k: 'transaccion' }, { h: 'Maestros', f: x => x.maestros.split(/\s*·\s*/).filter(Boolean).map(c => '<button class="btn sm ghost" data-action="mdgo" data-m="' + esc(c) + '">' + esc(c) + '</button>').join(' ') }, { h: 'Evento', f: x => '<span class="small muted">' + esc(x.evento) + '</span>' }], MODEL_TX, { cls: 'compact' }) + '</div>' +
    '<div class="card"><div class="card-h"><h2>Eventos de negocio</h2><span class="small muted">' + MODEL_EV.length + ' eventos</span></div>' + table([{ h: 'Evento', f: x => '<b class="mono">' + esc(x.codigo) + '</b>' }, { h: 'Etapa', k: 'etapa' }, { h: 'Nombre', f: x => '<b>' + esc(x.nombre) + '</b>' }, { h: 'Qué dispara', f: x => '<span class="small">' + esc(x.dispara) + '</span>' }], MODEL_EV, { cls: 'compact' }) + '</div></div>';
  return head + tabsHtml + body;
}
function reglasTable(list, abm) {
  return table([{ h: 'Maestro', f: x => x.maestro.split(/\s*·\s*/).map(c => c.startsWith('M-') ? '<button class="btn sm ghost" data-action="mdgo" data-m="' + esc(c) + '">' + esc(c) + '</button>' : esc(c)).join(' ') }, { h: 'Tipo', f: x => chip(x.tipo, x.tipo === 'Validación' ? 'crit' : x.tipo === 'Alerta' ? 'warn' : x.tipo === 'Automatización' ? 'acc' : 'info') }, { h: 'Código', f: x => '<span class="mono">' + esc(x.codigo) + '</span>' }, { h: 'Regla', f: x => '<b>' + esc(x.nombre) + '</b><br><span class="small">' + esc(x.controla) + '</span>' }, { h: 'Cuándo / quién', f: x => '<span class="small">' + esc(x.cuando) + '</span>' }, { h: 'Consecuencia', f: x => '<span class="small">' + esc(x.consecuencia) + '</span>' }, { h: 'Parámetro', f: x => '<span class="xs muted">' + esc(x.parametro) + '</span>' }, { h: 'TX', f: x => '<span class="xs muted">' + esc(x.tx) + '</span>' }, ...(abm ? [abmColModelo('RG')] : [])], list, { cls: 'compact', rowAttr: x => deBaja(x) ? 'style="opacity:.55"' : '' });
}
/* ABM de las listas del modelo — solo Máster data (S22) */
function abmBarModelo(m) {
  const rol = S.ctx.rol; const nv = nivelPermiso(permisoMD(m, rol)); const coll = MD_ABM[m].coll;
  return '<div class="btn-row" style="margin-bottom:8px;align-items:center">' + chip(rolName(rol) + ' · ' + nv.nombre, nv.cls, 'Las listas del modelo las administra Máster data') + (rol === 'MD' ? btn('Nuevo registro', 'md-nuevo', { m, coll }, 'sm pri') + '<span class="xs muted">Alta vigente, modificación versionada y baja lógica; queda en el registro de cambios. ' + sup('S22') + '</span>' : '<span class="xs muted">Solo consulta: el ABM de convenciones, reglas, definiciones y decisiones es de Máster data.</span>') + '</div>';
}
function abmColModelo(m) {
  return { h: 'registro', f: x => { const er = estadoRegistro(x); return (x._aud ? estadoChipMD(er) + (x._aud.version > 1 ? ' <span class="xs muted">v' + x._aud.version + '</span>' : '') : '<span class="xs muted">modelo v3.1</span>') + (S.ctx.rol === 'MD' && !deBaja(x) ? '<div class="btn-row" style="gap:3px;margin-top:3px">' + btn('Editar', 'md-editar', { m, id: x.id }, 'sm') + btn('Dar de baja', 'md-baja', { m, id: x.id }, 'sm danger') + '</div>' : ''); } };
}
function mdBrowser(MAP, fichas) {
  const rol = S.ctx.rol;
  if (S.ctx.mdM && !fichas.some(f => f.codigo === S.ctx.mdM) && mdFichas().some(f => f.codigo === S.ctx.mdM)) { const fh = mdFichas().find(f => f.codigo === S.ctx.mdM); return alertBox('crit', '<div><b>' + esc(fh.codigo + ' ' + fh.nombre) + '</b>: el rol <b>' + esc(rolName(rol)) + '</b> no visualiza este maestro (permiso "no lo visualiza", definido por Máster data). ' + sup('S17') + '</div>') + '<div class="btn-row" style="margin:10px 0">' + btn('Ver los maestros visibles', 'mdgo', { m: fichas[0]?.codigo || 'M-01' }, '') + '</div>'; }
  const sel0 = S.ctx.mdM && fichas.some(f => f.codigo === S.ctx.mdM) ? S.ctx.mdM : (fichas[0]?.codigo || 'M-01'); const f = fichas.find(x => x.codigo === sel0); const map = MAP[sel0];
  const sub = S.ctx.mdSub || 'REG'; const nivel = permisoMD(sel0, rol); const abm = MD_ABM[sel0] || {}; const puedeABM = nivel === 'abm' && mdColecciones(sel0).length > 0;
  const list = MODEL_DOMINIOS.map(dom => '<div class="grp">' + esc(dom) + '</div>' + fichas.filter(x => x.dominio === dom).map(x => { const n = (MAP[x.codigo]?.coll() || []).length; return '<button class="' + (x.codigo === sel0 ? 'on' : '') + '" data-action="mdgo" data-m="' + esc(x.codigo) + '"><span><span class="mono xs">' + esc(x.codigo) + '</span>' + (x.maqueta ? ' <span title="Agregado por la maqueta v2 (estructura nueva 15/09)" style="color:var(--brand)">★</span>' : '') + ' ' + esc(x.nombre) + '</span><span class="cnt" title="registros">' + n + '</span></button>'; }).join('')).join('');
  const regs = map ? map.coll() : []; const attrs = mdAtributos(sel0); const reglas = mdReglas(sel0); const txs = mdTx(sel0); const fuentes = MODEL_MAPEO.filter(x => x.maestro === sel0);
  const subTabs = [['REG', 'Registros (' + regs.length + ')'], ['ATR', 'Atributos (' + attrs.length + ')'], ['REGL', 'Reglas (' + reglas.length + ')'], ['FUE', 'Fuentes (' + fuentes.length + ')'], ['TX', 'Transacciones (' + txs.length + ')']];
  const ficha = '<div class="card"><div class="card-h"><h2><span class="mono">' + esc(f.codigo) + '</span> ' + esc(f.nombre) + (f.maqueta ? ' ' + chip('agregado por la maqueta', 'warn') : '') + '</h2><span class="small muted">' + esc(f.dominio) + ' · nivel ' + f.nivel + '</span></div><p class="small" style="margin-bottom:10px">' + esc(f.descripcion) + '</p>' +
    '<div class="grid g2">' + kv([['Clave natural', '<span class="mono">' + esc(f.clave) + '</span>'], ['Depende de', esc(f.depende)], ['Existe hoy', esc(f.existeHoy)], ['Administra', esc(f.administra)], ['Autoriza', esc(f.autoriza)]]) + kv([['Equivalente v2.2', esc(f.equivV22)], ['Transacciones que lo consumen', '<span class="small">' + esc(f.transacciones) + '</span>'], ['Nº atributos (modelo)', f.nAtributos], ['Fuente de carga inicial', '<span class="small">' + esc(f.fuenteCarga) + '</span>'], f.comentario ? ['Comentario', '<span class="small muted">' + esc(f.comentario) + '</span>'] : null]) + '</div>' +
    (map?.nota ? '<p class="help" style="margin-top:10px">' + map.nota + '</p>' : '') + '</div>';
  let detail = '';
  if (sub === 'REG') {
    /* barra de ABM según el permiso del rol (SUPUESTO S17) */
    const nv = nivelPermiso(nivel); let bar = '<div class="btn-row" style="margin-bottom:8px;align-items:center">' + chip(rolName(rol) + ' · ' + nv.nombre, nv.cls, 'Permiso del rol activo sobre este maestro, definido por Máster data');
    if (puedeABM) bar += mdColecciones(sel0).map(t => btn('Nuevo registro' + (mdColecciones(sel0).length > 1 ? ': ' + t.v : ''), 'md-nuevo', { m: sel0, coll: t.coll }, 'sm pri')).join('') + (rol !== 'MD' ? '<span class="xs muted">Las altas y modificaciones de ' + esc(rolName(rol)) + ' nacen "en validación" hasta que Máster data las publica.</span>' : '');
    else if (abm.pantalla) bar += btn(abm.pantalla === 'arribos' ? 'Ir a Logística de arribo' : 'Ir a Administración', 'go', { screen: abm.pantalla, admtab: abm.admTab || '' }, 'sm') + '<span class="xs muted">' + esc(abm.txt) + '</span>';
    else if (abm.derivado) bar += '<span class="xs muted">' + esc(abm.derivado) + '</span>';
    else if (nivel === 'abm') bar += '<span class="xs muted">Este maestro no tiene ABM directo en la maqueta.</span>';
    else bar += '<span class="xs muted">Solo consulta para ' + esc(rolName(rol)) + '; el ABM lo hace Máster data o un rol con permiso.</span>';
    bar += '</div>';
    if (!map) detail = bar + alertBox('warn', 'La maqueta no tiene registros de este maestro.');
    else { const cols = map.cols.map(c => ({ h: c.a, f: c.f })); if (map.extra) cols.push(...map.extra); if (map.acciones) cols.push({ h: '', f: map.acciones });
      if (mdColecciones(sel0).length) cols.push({ h: 'registro (auditoría)', f: x => { const er = estadoRegistro(x); const c = mdCollDe(sel0, x.id); const own = c && (c.rec._aud); return (own || er !== 'vigente' ? estadoChipMD(er) + (x._aud?.version > 1 ? ' <span class="xs muted">v' + x._aud.version + '</span>' : '') : '<span class="xs muted">vigente · migración</span>') + (puedeABM && c ? '<div class="btn-row" style="gap:3px;margin-top:3px">' + (deBaja(x) ? '' : btn('Editar', 'md-editar', { m: sel0, id: x.id }, 'sm') + btn('Dar de baja', 'md-baja', { m: sel0, id: x.id }, 'sm danger')) + (rol === 'MD' && enValidacion(x) ? btn('Validar', 'md-validar', { m: sel0, id: x.id }, 'sm pri') + btn('Rechazar', 'md-rechazar', { m: sel0, id: x.id }, 'sm danger') : '') + '</div>' : ''); } });
      detail = bar + table(cols, regs, { cls: 'compact', empty: 'Sin registros en el contexto actual', rowAttr: x => deBaja(x) ? 'style="opacity:.55"' : '' }) + '<p class="help" style="margin-top:6px">Las columnas llevan el nombre del atributo del modelo; "calc." = calculado por el sistema; las referencias a otros maestros se muestran con su código. La baja es lógica: el registro queda "dada de baja", se conserva y deja de ofrecerse en la planificación.</p>'; }
  } else if (sub === 'ATR') {
    const mapped = new Set((map?.cols || []).map(c => c.a));
    detail = table([{ h: 'Nº', cls: 'num', f: x => x.n }, { h: 'Atributo', f: x => '<b class="mono">' + esc(x.atributo) + '</b>' + (x.star ? ' <span class="sup" title="Propuesto por el simulador / la maqueta: a validar">★</span>' : '') }, { h: 'Tipo de dato', k: 'tipo' }, { h: 'Obligatorio', f: x => x.obligatorio === 'Sí' ? chip('Sí', 'acc') : esc(x.obligatorio) }, { h: 'Dominio / validación', f: x => '<span class="small">' + esc(x.dominio) + '</span>' }, { h: 'Parámetro', f: x => x.parametro === 'Sí' ? chip('Sí', 'info') : '<span class="dim">No</span>' }, { h: 'Regla / observación', f: x => '<span class="small">' + esc(x.regla) + '</span>' }, { h: 'Origen', f: x => '<span class="xs muted">' + esc(x.origen) + '</span>' }, { h: 'Carácter', f: x => chip(x.caracter, x.caracter === 'propio' ? '' : 'info') }, { h: 'Equivalente v2.2', f: x => '<span class="xs muted">' + esc(x.equivV22) + '</span>' }, { h: 'En la maqueta', f: x => mapped.has(x.atributo) ? chip('en registros', 'ok') : x.caracter === 'calculado' ? chip('calculado', 'info') : chip('definido, sin uso aún', 'warn') }], attrs, { cls: 'compact' }) +
      '<p class="help" style="margin-top:6px">"En registros": el atributo se muestra en la pestaña Registros con datos de la maqueta. "Definido, sin uso aún": está en el modelo y en la master data de la maqueta, pero ningún circuito lo usa todavía (insumo del fit-gap).</p>';
  } else if (sub === 'REGL') detail = reglas.length ? reglasTable(reglas) : '<p class="muted">El modelo no define reglas específicas para este maestro (aplican las comunes: ciclo de vida ABM-0 y convenciones).</p>';
  else if (sub === 'FUE') detail = fuentes.length ? table([{ h: 'Atributo destino', f: x => '<b class="mono">' + esc(x.atributo) + '</b>' }, { h: 'Fuente 1 · campo', f: x => esc(x.fuente1) + (x.campo1 ? '<br><span class="xs muted">' + esc(x.campo1) + '</span>' : '') }, { h: 'Fuente 2 · campo', f: x => esc(x.fuente2) + (x.campo2 ? '<br><span class="xs muted">' + esc(x.campo2) + '</span>' : '') }, { h: 'Regla', f: x => '<span class="small">' + esc(x.regla) + '</span>' }], fuentes, { cls: 'compact' }) : '<p class="muted">Sin mapeo de fuentes específico; ver "Fuente de carga inicial" en la ficha.</p>';
  else if (sub === 'TX') detail = txs.length ? table([{ h: 'Código', f: x => '<b class="mono">' + esc(x.codigo) + '</b>' }, { h: 'Etapa', f: x => '<span class="small">' + esc(x.etapa) + '</span>' }, { h: 'Transacción', k: 'transaccion' }, { h: 'Evento', f: x => '<span class="small muted">' + esc(x.evento) + '</span>' }], txs, { cls: 'compact' }) : '<p class="muted">Ninguna transacción del catálogo referencia este maestro' + (f.maqueta ? ' (lo consumen las acciones de la orden de servicio de la maqueta)' : '') + '.</p>';
  /* en pantallas chicas la lista lateral se reemplaza por un selector */
  const mdSel = '<label class="field md-sel"><span>Maestro</span><select data-mdsel="1">' + MODEL_DOMINIOS.map(dom => '<optgroup label="' + esc(dom) + '">' + fichas.filter(x => x.dominio === dom).map(x => '<option value="' + esc(x.codigo) + '"' + (x.codigo === sel0 ? ' selected' : '') + '>' + esc(x.codigo + ' · ' + x.nombre) + ' (' + (MAP[x.codigo]?.coll() || []).length + ')</option>').join('') + '</optgroup>').join('') + '</select></label>';
  return '<div class="mdb">' + mdSel + '<nav class="mdnav">' + list + '</nav><div class="stack" style="min-width:0">' + ficha + '<div class="card"><div class="tabs" style="margin-bottom:10px">' + subTabs.map(([id, n]) => '<button class="' + (sub === id ? 'on' : '') + '" data-action="mdsub" data-sub="' + id + '">' + n + '</button>').join('') + '</div>' + detail + '</div></div></div>';
}
function mdPorArea(MAP, fichas) {
  const areas = [
    ['Generales del ERP', ['M-01', 'M-35', 'M-05', 'M-38', 'M-02', 'M-03', 'M-04', 'M-06', 'M-07', 'M-18', 'M-14', 'M-37', 'M-36'], 'Entidades, BU, departamentos, centros de costo; usuarios, roles y permisos; clientes, proveedores y empresas del grupo; productos, unidades y monedas; catálogo de servicios; workflows.'],
    ['Comercial', ['M-16', 'M-15', 'M-22', 'M-06'], 'Instrumentos contractuales y adendas, tarifas, condiciones, despachantes y relaciones entre clientes, productos y servicios.'],
    ['Logística de arribo', ['M-17', 'M-31', 'M-32', 'M-08', 'M-21'], 'Lineup, cupos de camiones, operativos ferroviarios, buques y agencias.'],
    ['Áreas y capacidad', ['M-39', 'M-12', 'M-10a', 'M-13', 'M-26'], 'Sectores que administran su capacidad y reservan para operativos futuros (Logística, Rental, Depósitos, RRHH, Portería y balanza).'],
    ['Planificación', ['M-25', 'M-12', 'M-10', 'M-10a', 'M-26', 'M-11', 'M-09', 'M-20', 'M-24'], 'Muelles, equipos de descarga / carga, depósitos y ubicaciones, balanzas, recursos logísticos, plantas, tolerancias y compatibilidades.'],
    ['Personal', ['M-05', 'M-28', 'M-13', 'M-27', 'M-33', 'M-19'], 'Funciones y puestos, personal propio, manos y proveedores de personal, choferes, régimen de turnos y calendario.'],
    ['Operaciones', ['M-29', 'M-20', 'M-30'], 'Causas de demora, tolerancias, motivos de modificación e insumos.'],
    ['Depósito', ['M-10', 'M-10a', 'M-23', 'M-24'], 'Ubicaciones, capacidades, restricciones, calidad y compatibilidad.'],
    ['Seguridad', ['M-34'], 'Métodos seguros por producto, familia y recurso; de aquí se deriva la habilitación de cada orden.'],
  ];
  return '<div class="stack">' + areas.map(([n, ms, d]) => '<div class="card"><div class="card-h"><h2>' + esc(n) + '</h2><span class="small muted">' + esc(d) + '</span></div><div class="btn-row">' + ms.map(c => { const f = fichas.find(x => x.codigo === c); return f ? '<button class="btn sm" data-action="mdgo" data-m="' + esc(c) + '"><span class="mono xs">' + esc(c) + '</span>&nbsp;' + esc(f.nombre) + ' <span class="cnt" style="font-family:var(--mono);font-size:10.5px;background:var(--surface-3);padding:0 6px;border-radius:9px">' + (MAP[c]?.coll() || []).length + '</span></button>' : ''; }).join('') + '</div></div>').join('') +
    '<div class="card"><div class="card-h"><h2>Parámetros del motor de recomendación</h2><span class="small muted">' + sup('S2') + '</span></div>' + kv([['Pesos del puntaje', 'costo ' + fmtPct(md().parametros.pesos.costo) + ' · duración ' + fmtPct(md().parametros.pesos.duracion) + ' · cumplimiento ' + fmtPct(md().parametros.pesos.cumplimiento)], ['Eficiencia de equipos', fmtPct(md().parametros.eficienciaEquipo)], ['Origen de equipos por defecto', esc(md().parametros.origenEquiposPorDefecto) + ' ' + sup('S14')], ['Turno', md().turnos.duracionH + ' h · ' + md().turnos.porDia + ' por día (M-33)'], ['Motivos de modificación', esc(md().motivosModificacion.join(' · '))], ['Motivos de desvío del plan', esc(md().motivosDesvioPlan.join(' · '))], ['Editar', btn('Administración › Parámetros', 'go', { screen: 'admin', admtab: 'PAR' }, 'sm ghost')]]) + '</div></div>';
}

/* ---------- Permisos por rol (maestro × rol · oculto / consulta / abm) — edita Máster data (SUPUESTO S17) ---------- */
function mdPermisos(fichas) {
  const roles = md().roles.filter(r => r.id !== 'MD'); const esMD = S.ctx.rol === 'MD';
  const cell = (m, r) => { const n = permisoMD(m, r.id); const nv = nivelPermiso(n); return esMD ? sel('perm-' + m + '-' + r.id, NIVELES_PERMISO.map(x => ({ v: x.id, t: x.nombre })), n, 'data-perm="' + m + ':' + r.id + '" class="perm ' + n + '"') : chip(nv.nombre, nv.cls); };
  const rows = MODEL_DOMINIOS.map(dom => '<tr><td colspan="' + (roles.length + 2) + '" class="grp-row">' + esc(dom) + '</td></tr>' + fichas.filter(f => f.dominio === dom).map(f => '<tr><td><button class="btn sm ghost" data-action="mdgo" data-m="' + esc(f.codigo) + '"><span class="mono xs">' + esc(f.codigo) + '</span>&nbsp;' + esc(f.nombre) + '</button></td>' + roles.map(r => '<td class="center">' + cell(f.codigo, r) + '</td>').join('') + '<td class="center">' + chip('Puede ABM', 'acc', 'Máster data siempre administra todos los maestros') + '</td></tr>').join('')).join('');
  return '<div class="card"><div class="card-h"><h2>Permisos por maestro y rol</h2><span class="small muted">' + (esMD ? 'Cambiá el nivel en cada celda: el cambio aplica de inmediato y queda en el registro de cambios.' : 'Solo Máster data modifica los permisos; cambiá el rol activo a Máster data para editarlos.') + '</span></div>' +
    '<div class="stack" style="gap:3px;margin-bottom:10px">' + NIVELES_PERMISO.map(n => '<div>' + chip(n.nombre, n.cls) + ' <span class="xs muted">' + esc(({ oculto: 'el maestro no aparece en Datos maestros ni en los enlaces del rol', consulta: 've ficha, atributos y registros; sin ABM', abm: 'alta, modificación y baja lógica; sus altas nacen en validación hasta que Máster data las publica' })[n.id]) + '</span></div>').join('') + '</div>' +
    '<div class="tw"><table class="t compact"><thead><tr><th>Maestro</th>' + roles.map(r => '<th class="center">' + esc(r.nombre) + '<br><span class="xs dim">' + esc(r.usuario) + '</span></th>').join('') + '<th class="center">Máster data</th></tr></thead><tbody>' + rows + '</tbody></table></div>' +
    '<p class="help" style="margin-top:8px">' + sup('S17') + ' Los permisos iniciales son de demostración: cada área administra los maestros de su ámbito (Comercial: clientes, contratos, tarifas, despachantes; Logística de arribo: buques, lineup, agencias, cupos y trenes; Depósito: depósitos y ubicaciones, calidad y compatibilidad; Operaciones: equipos, causas de demora e insumos; Planificador: tolerancias y compatibilidad) y no visualiza los maestros contables que no le corresponden.</p></div>';
}
